server:
  port: 8089

spring:
  mvc:
    static-path-pattern: /static/**

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level [%15thread] %-50.50(%logger{39}.%method:%-3line) - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level [%15thread] %-50.50(%logger{39}.%method:%-3line) - %msg%n"
  file:
    name: ./logs/rtsp-websocket-server-starter/rtsp-websocket-server-starter.log
  level:
    com.github.xingshuangs: debug

rtsp:
  addresses:
    - number: 1001
      url: rtsp://admin:hb123456@192.168.3.251:554/h264/ch1/main/av_stream
    - number: 1002
      url: rtsp://admin:hb123456@192.168.3.250:554/h264/ch1/main/av_stream
    - number: 1003
      url: rtsp://admin:123456@192.168.3.142:554/h264/ch1/main/av_stream
    - number: 1004
      url: rtsp://admin:123456@192.168.3.142:554/h264/ch2/main/av_stream