server:
  port: 8089

spring:
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    com.github.xingshuangs: debug

rtsp:
  addresses:
    - name: address1
      url: rtsp://admin:hb123456@192.168.3.251:554/h264/ch1/main/av_stream
    - name: address2
      url: rtsp://admin:hb123456@192.168.3.250:554/h264/ch1/main/av_stream